# Based on https://github.com/FabricMC/fabric-language-kotlin/blob/master/.github/workflows/release.yml
name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
          cache-dependency-path: |
            **/build.gradle*
            **/gradle.properties
            settings.gradle*
            **/gradle-wrapper.properties
      - uses: shurik204/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew build publishMods --stacktrace --no-daemon
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}